version: '3'
services:
  postgres:
    image: postgres
    container_name: pp-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: private-pension-api
    container_name: pp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
